/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppMembersRouteImport } from './routes/_app/members'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppServersIdRouteImport } from './routes/_app/servers/$id'
import { Route as AppServersIdSettingsRouteImport } from './routes/_app/servers/$id/settings'
import { Route as AppServersIdPluginsRouteImport } from './routes/_app/servers/$id/plugins'
import { Route as AppServersIdRuntimeRouteImport } from './routes/_app/servers/$id/runtime'
import { Route as AppServersIdScheduleRouteImport } from './routes/_app/servers/$id/schedule'
import { Route as AppServersIdWebhooksRouteImport } from './routes/_app/servers/$id/webhooks'
import { Route as AppServersIdWhitelistRouteImport } from './routes/_app/servers/$id/whitelist'
import { Route as AppServersIdPlayersRouteImport } from './routes/_app/servers/$id/players'
import { Route as AppServersIdMapRouteImport } from './routes/_app/servers/$id/map'
import { Route as AppServersIdFilesRouteImport } from './routes/_app/servers/$id/files'
import { Route as AppServersIdConsoleRouteImport } from './routes/_app/servers/$id/console'
import { Route as AppServersIdBackupsRouteImport } from './routes/_app/servers/$id/backups'
import { Route as AppServersIdAnalyticsRouteImport } from './routes/_app/servers/$id/analytics'
import { Route as AppServersIdAlertsRouteImport } from './routes/_app/servers/$id/alerts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppServersIdRoute = AppServersIdRouteImport.update({
  id: '/servers/$id',
  path: '/servers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppServersIdSettingsRoute = AppServersIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppServersIdRoute,
} as any)
const AppServersIdPluginsRoute = AppServersIdPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AppServersIdRoute,
} as any)
const AppServersIdRuntimeRoute = AppServersIdRuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => AppServersIdRoute,
} as any)
const AppServersIdScheduleRoute = AppServersIdScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppServersIdRoute,
} as any)
const AppServersIdWebhooksRoute = AppServersIdWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppServersIdRoute,
} as any)
const AppServersIdWhitelistRoute = AppServersIdWhitelistRouteImport.update({
  id: '/whitelist',
  path: '/whitelist',
  getParentRoute: () => AppServersIdRoute,
} as any)
const AppServersIdPlayersRoute = AppServersIdPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AppServersIdRoute,
} as any)
const AppServersIdMapRoute = AppServersIdMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppServersIdRoute,
} as any)
const AppServersIdFilesRoute = AppServersIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppServersIdRoute,
} as any)
const AppServersIdConsoleRoute = AppServersIdConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AppServersIdRoute,
} as any)
const AppServersIdBackupsRoute = AppServersIdBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AppServersIdRoute,
} as any)
const AppServersIdAnalyticsRoute = AppServersIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppServersIdRoute,
} as any)
const AppServersIdAlertsRoute = AppServersIdAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppServersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/members': typeof AppMembersRoute
  '/servers/$id': typeof AppServersIdRouteWithChildren
  '/servers/$id/alerts': typeof AppServersIdAlertsRoute
  '/servers/$id/analytics': typeof AppServersIdAnalyticsRoute
  '/servers/$id/backups': typeof AppServersIdBackupsRoute
  '/servers/$id/console': typeof AppServersIdConsoleRoute
  '/servers/$id/files': typeof AppServersIdFilesRoute
  '/servers/$id/map': typeof AppServersIdMapRoute
  '/servers/$id/players': typeof AppServersIdPlayersRoute
  '/servers/$id/plugins': typeof AppServersIdPluginsRoute
  '/servers/$id/runtime': typeof AppServersIdRuntimeRoute
  '/servers/$id/schedule': typeof AppServersIdScheduleRoute
  '/servers/$id/webhooks': typeof AppServersIdWebhooksRoute
  '/servers/$id/whitelist': typeof AppServersIdWhitelistRoute
  '/servers/$id/settings': typeof AppServersIdSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/members': typeof AppMembersRoute
  '/': typeof AppIndexRoute
  '/servers/$id': typeof AppServersIdRouteWithChildren
  '/servers/$id/alerts': typeof AppServersIdAlertsRoute
  '/servers/$id/analytics': typeof AppServersIdAnalyticsRoute
  '/servers/$id/backups': typeof AppServersIdBackupsRoute
  '/servers/$id/console': typeof AppServersIdConsoleRoute
  '/servers/$id/files': typeof AppServersIdFilesRoute
  '/servers/$id/map': typeof AppServersIdMapRoute
  '/servers/$id/players': typeof AppServersIdPlayersRoute
  '/servers/$id/plugins': typeof AppServersIdPluginsRoute
  '/servers/$id/runtime': typeof AppServersIdRuntimeRoute
  '/servers/$id/settings': typeof AppServersIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/servers/$id': typeof AppServersIdRouteWithChildren
  '/_app/servers/$id/alerts': typeof AppServersIdAlertsRoute
  '/_app/servers/$id/analytics': typeof AppServersIdAnalyticsRoute
  '/_app/servers/$id/backups': typeof AppServersIdBackupsRoute
  '/_app/servers/$id/console': typeof AppServersIdConsoleRoute
  '/_app/servers/$id/files': typeof AppServersIdFilesRoute
  '/_app/servers/$id/map': typeof AppServersIdMapRoute
  '/_app/servers/$id/players': typeof AppServersIdPlayersRoute
  '/_app/servers/$id/plugins': typeof AppServersIdPluginsRoute
  '/_app/servers/$id/runtime': typeof AppServersIdRuntimeRoute
  '/_app/servers/$id/schedule': typeof AppServersIdScheduleRoute
  '/_app/servers/$id/webhooks': typeof AppServersIdWebhooksRoute
  '/_app/servers/$id/whitelist': typeof AppServersIdWhitelistRoute
  '/_app/servers/$id/settings': typeof AppServersIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/members'
    | '/servers/$id'
    | '/servers/$id/alerts'
    | '/servers/$id/analytics'
    | '/servers/$id/backups'
    | '/servers/$id/console'
    | '/servers/$id/files'
    | '/servers/$id/map'
    | '/servers/$id/players'
    | '/servers/$id/plugins'
    | '/servers/$id/runtime'
    | '/servers/$id/schedule'
    | '/servers/$id/webhooks'
    | '/servers/$id/whitelist'
    | '/servers/$id/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit'
    | '/members'
    | '/'
    | '/servers/$id'
    | '/servers/$id/alerts'
    | '/servers/$id/analytics'
    | '/servers/$id/backups'
    | '/servers/$id/console'
    | '/servers/$id/files'
    | '/servers/$id/map'
    | '/servers/$id/players'
    | '/servers/$id/plugins'
    | '/servers/$id/runtime'
    | '/servers/$id/schedule'
    | '/servers/$id/webhooks'
    | '/servers/$id/whitelist'
    | '/servers/$id/settings'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/audit'
    | '/_app/members'
    | '/_app/'
    | '/_app/servers/$id'
    | '/_app/servers/$id/alerts'
    | '/_app/servers/$id/analytics'
    | '/_app/servers/$id/backups'
    | '/_app/servers/$id/console'
    | '/_app/servers/$id/files'
    | '/_app/servers/$id/map'
    | '/_app/servers/$id/players'
    | '/_app/servers/$id/plugins'
    | '/_app/servers/$id/runtime'
    | '/_app/servers/$id/schedule'
    | '/_app/servers/$id/webhooks'
    | '/_app/servers/$id/whitelist'
    | '/_app/servers/$id/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers/$id': {
      id: '/_app/servers/$id'
      path: '/servers/$id'
      fullPath: '/servers/$id'
      preLoaderRoute: typeof AppServersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers/$id/settings': {
      id: '/_app/servers/$id/settings'
      path: '/settings'
      fullPath: '/servers/$id/settings'
      preLoaderRoute: typeof AppServersIdSettingsRouteImport
      parentRoute: typeof AppServersIdRoute
    }
    '/_app/servers/$id/plugins': {
      id: '/_app/servers/$id/plugins'
      path: '/plugins'
      fullPath: '/servers/$id/plugins'
      preLoaderRoute: typeof AppServersIdPluginsRouteImport
      parentRoute: typeof AppServersIdRoute
    }
    '/_app/servers/$id/players': {
      id: '/_app/servers/$id/players'
      path: '/players'
      fullPath: '/servers/$id/players'
      preLoaderRoute: typeof AppServersIdPlayersRouteImport
      parentRoute: typeof AppServersIdRoute
    }
    '/_app/servers/$id/map': {
      id: '/_app/servers/$id/map'
      path: '/map'
      fullPath: '/servers/$id/map'
      preLoaderRoute: typeof AppServersIdMapRouteImport
      parentRoute: typeof AppServersIdRoute
    }
    '/_app/servers/$id/files': {
      id: '/_app/servers/$id/files'
      path: '/files'
      fullPath: '/servers/$id/files'
      preLoaderRoute: typeof AppServersIdFilesRouteImport
      parentRoute: typeof AppServersIdRoute
    }
    '/_app/servers/$id/console': {
      id: '/_app/servers/$id/console'
      path: '/console'
      fullPath: '/servers/$id/console'
      preLoaderRoute: typeof AppServersIdConsoleRouteImport
      parentRoute: typeof AppServersIdRoute
    }
    '/_app/servers/$id/backups': {
      id: '/_app/servers/$id/backups'
      path: '/backups'
      fullPath: '/servers/$id/backups'
      preLoaderRoute: typeof AppServersIdBackupsRouteImport
      parentRoute: typeof AppServersIdRoute
    }
    '/_app/servers/$id/analytics': {
      id: '/_app/servers/$id/analytics'
      path: '/analytics'
      fullPath: '/servers/$id/analytics'
      preLoaderRoute: typeof AppServersIdAnalyticsRouteImport
      parentRoute: typeof AppServersIdRoute
    }
    '/_app/servers/$id/alerts': {
      id: '/_app/servers/$id/alerts'
      path: '/alerts'
      fullPath: '/servers/$id/alerts'
      preLoaderRoute: typeof AppServersIdAlertsRouteImport
      parentRoute: typeof AppServersIdRoute
    }
    '/_app/servers/$id/runtime': {
      id: '/_app/servers/$id/runtime'
      path: '/runtime'
      fullPath: '/servers/$id/runtime'
      preLoaderRoute: typeof AppServersIdRuntimeRouteImport
      parentRoute: typeof AppServersIdRoute
    }
    '/_app/servers/$id/schedule': {
      id: '/_app/servers/$id/schedule'
      path: '/schedule'
      fullPath: '/servers/$id/schedule'
      preLoaderRoute: typeof AppServersIdScheduleRouteImport
      parentRoute: typeof AppServersIdRoute
    }
    '/_app/servers/$id/webhooks': {
      id: '/_app/servers/$id/webhooks'
      path: '/webhooks'
      fullPath: '/servers/$id/webhooks'
      preLoaderRoute: typeof AppServersIdWebhooksRouteImport
      parentRoute: typeof AppServersIdRoute
    }
    '/_app/servers/$id/whitelist': {
      id: '/_app/servers/$id/whitelist'
      path: '/whitelist'
      fullPath: '/servers/$id/whitelist'
      preLoaderRoute: typeof AppServersIdWhitelistRouteImport
      parentRoute: typeof AppServersIdRoute
    }
  }
}

interface AppServersIdRouteChildren {
  AppServersIdAlertsRoute: typeof AppServersIdAlertsRoute
  AppServersIdAnalyticsRoute: typeof AppServersIdAnalyticsRoute
  AppServersIdBackupsRoute: typeof AppServersIdBackupsRoute
  AppServersIdConsoleRoute: typeof AppServersIdConsoleRoute
  AppServersIdFilesRoute: typeof AppServersIdFilesRoute
  AppServersIdMapRoute: typeof AppServersIdMapRoute
  AppServersIdPlayersRoute: typeof AppServersIdPlayersRoute
  AppServersIdPluginsRoute: typeof AppServersIdPluginsRoute
  AppServersIdRuntimeRoute: typeof AppServersIdRuntimeRoute
  AppServersIdScheduleRoute: typeof AppServersIdScheduleRoute
  AppServersIdWebhooksRoute: typeof AppServersIdWebhooksRoute
  AppServersIdWhitelistRoute: typeof AppServersIdWhitelistRoute
  AppServersIdSettingsRoute: typeof AppServersIdSettingsRoute
}

const AppServersIdRouteChildren: AppServersIdRouteChildren = {
  AppServersIdAlertsRoute: AppServersIdAlertsRoute,
  AppServersIdAnalyticsRoute: AppServersIdAnalyticsRoute,
  AppServersIdBackupsRoute: AppServersIdBackupsRoute,
  AppServersIdConsoleRoute: AppServersIdConsoleRoute,
  AppServersIdFilesRoute: AppServersIdFilesRoute,
  AppServersIdMapRoute: AppServersIdMapRoute,
  AppServersIdPlayersRoute: AppServersIdPlayersRoute,
  AppServersIdPluginsRoute: AppServersIdPluginsRoute,
  AppServersIdRuntimeRoute: AppServersIdRuntimeRoute,
  AppServersIdScheduleRoute: AppServersIdScheduleRoute,
  AppServersIdWebhooksRoute: AppServersIdWebhooksRoute,
  AppServersIdWhitelistRoute: AppServersIdWhitelistRoute,
  AppServersIdSettingsRoute: AppServersIdSettingsRoute,
}

const AppServersIdRouteWithChildren = AppServersIdRoute._addFileChildren(
  AppServersIdRouteChildren,
)

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppMembersRoute: typeof AppMembersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppServersIdRoute: typeof AppServersIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppMembersRoute: AppMembersRoute,
  AppIndexRoute: AppIndexRoute,
  AppServersIdRoute: AppServersIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
